name: DeploymentPipeline

on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Install Packages
        run: npm ci
      - name: Build
        run: react-scripts build && rm -rf docs && mv build docs
